name: Production Deployment

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Typecheck
        run: npm run typecheck

      - name: Set API base URL for prod
        run: echo "VITE_BACKEND_URL=https://curatedcompass.in" >> .env

      - name: Build production
        run: |
          npm run build
          npm run postbuild
          # Verify source maps exist
          ls -la dist/assets/*.map
          
          # Run analysis with explicit source map paths
          npx source-map-explorer dist/assets/*.js dist/assets/*.js.map

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
